version: '3'

services:
  api:
    image: golang:latest
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - GIN_MODE=debug
    command: sh -c "go mod tidy && go run cmd/api/main.go"
    restart: unless-stopped
